### ISSUE TITLE
Small Typo: Company A vs Company B swap

### ISSUE THREAD

**Issue by rasbt** [chiphuyen/ml-interviews-book#10]
Hi Chip,

this is a really great book. Thanks for sharing it with the world!

I think there is small typo where A should be swapped with B:

>  ... companies as design partners is a really good sign for A.

In: https://github.com/chiphuyen/ml-interviews-book/blob/master/contents/1.2.1-applications-companies-vs.-tooling-companies.md

**Comment by chiphuyen** [comment]
Will be fixed in the next PR. Thanks for pointing this out!
