### ISSUE TITLE
Small Typo in "1.1.3.2 Machine learning engineer vs. software engineer"

### ISSUE THREAD

**Issue by pg1647** [chiphuyen/ml-interviews-book#12]
Great book, just found a small typo so I thought I will let you know so that you can make this book even better than it already is:

In this line: "Some just add an interview specially focused on ML on top of their existing interview process for **ML**, making their MLE process a bit longer than their SWE process.", the highlighted word **ML** should be **SWE** in my opinion.

**Comment by chiphuyen** [comment]
Merging the PR now!
