### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ammarasmro** [chiphuyen/ml-interviews-book#3]
Link for post in this line

>Akihiro Matsukawa gave an interesting perspective on the difference between the research scientist and the research engineer with his post: Research Engineering FAQs.

Goes to this link: https://mtskw.com/re/

Which doesn't work

Link to content: https://github.com/chiphuyen/ml-interviews-book/blob/master/contents/1.1.2.2-research-scientist-vs.-research-engineer.md

Error:
![image](https://user-images.githubusercontent.com/22536934/123199570-1c8dfd00-d47d-11eb-9180-59aebd9bc3e7.png)

**Comment by ashnair1** [comment]
The correct link is https://mtskw.com/posts/re/

#1 fixes this

**Comment by chiphuyen** [comment]
Will be fixed in the next PR. Thanks for pointing this out!
