### ISSUE TITLE
Dead link to course: Probability and Statistics by Stanford Online

### ISSUE THREAD

**Issue by sajal2692** [chiphuyen/ml-interviews-book#35]
In the courses page, the link to the Probability and Statistics course is dead/leads to a 404.

Original link: https://online.stanford.edu/courses/gse-yprobstat-probability-and-statistics

I think that this Coursera course from Stanford: https://www.coursera.org/learn/stanford-statistics is equivalent. The course is free for audit (access to all lectures and reading materials). Raised a PR with this change.

**Comment by ltngonnguyen** [comment]
> updated. thank you!

Would be great if you can update here as well :) https://huyenchip.com/2019/08/05/free-online-machine-learning-curriculum.html
